name: Build

on:
  workflow_run:
    workflows: ['Update']
    types: [completed]
  push:
    tags: ['*']

env:
  image_name: kostrykin/galaxy-image-analysis

permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          gh run download ${{ github.event.workflow_run.id }} --dir temp
          ls -al temp

      - name: Get tag artifact from Release workflow
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v7
        with:
          name: tag-name
          path: .
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get tag name
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            if [[ ! -f tag.txt ]]; then
              ls -al
              exit 1
            fi
            echo "tag=$(cat tag.txt)" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.check.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ steps.check.outputs.tag }}
