name: Test

on:
  pull_request:
    branches: ['main']

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Fetch tools
        run: |
          python scripts/fetch-tools.py tools.yml --verbose 2> >(tee stderr.txt >&2)
          if [ -s "stderr.txt" ]; then
            exit 1
          fi

      - name: Test scripts/check-rebuild.py
        run: |
          python scripts/check-rebuild.py tools.yml

      - name: Test scripts/get-tag.py
        run: |
          python scripts/get-tag.py

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: sed -i 's|^RUN\s*install-tools.*||' Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
